version: '3.1'
services:
    mailhog:
      image: 'mailhog/mailhog:latest'
      container_name: mail_defiantdev
      ports:
          - '1112:8025'
      networks:
        - defiantdev

    mysql:
      image: 'mysql:8.0'
      working_dir: /application
      container_name: mysql_defiantdev
      restart: unless-stopped
      tty: true
      volumes:
          - '.:/application'
      environment:
          - MYSQL_ROOT_PASSWORD=secret
          - MYSQL_DATABASE=defiantdevdb
          - MYSQL_USER=defiantdevuser
          - MYSQL_PASSWORD=secret
      ports:
          - '3306:3306'
      networks:
        - defiantdev

    webserver:
      image: 'nginx:alpine'
      working_dir: /application
      container_name: webserver_defiantdev
      volumes:
          - '.:/application'
          - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      ports:
          - '1111:80'
      networks:
        - defiantdev

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php_defiantdev
      working_dir: /application
      volumes:
          - '.:/application'
          - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
      networks:
        - defiantdev

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      working_dir: /application
      restart: always
      container_name: phpmyadmin_defiantdev
      environment:
        PMA_HOST: mysql_defiantdev
        PMA_USER: root
        PMA_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
      ports:
        - "2222:80"
      networks:
        - defiantdev

networks:
  defiantdev:
    driver: bridge
